# This file was generated by cli/scripts/release-cask. DO NOT EDIT.
cask "kapten" do
  version "0.1.0-rc.3"

  on_macos do
    on_arm do
      sha256 "fcdae21745c948f953d38379ef549db60682167123402a65330a854faea96940"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a1f25282af1669517b8b785af05f08bfb936bebd8a2accae7acb0f579103c3f"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b3d75bc1cd9fc60a59699498593d712ae41ea61459dd1ca1bd78e596d8190adf"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "67d054da76f55619e19d3a98fb498428159f296f1c25a2284ed91a91156827c0"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kapten"
  desc "Manage Kapten resources from the command line"
  homepage "https://github.com/kapten-io/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapten"
  binary "restish-mcp"
end
