# This file was generated by cli/scripts/release-cask. DO NOT EDIT.
cask "kapten" do
  version "0.1.0-rc.4"

  on_macos do
    on_arm do
      sha256 "6aabbf64f0753b0dcc0865d538bf077453e81f2af61c4563e1d4cebe4bde48d1"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bee84e43ae99d35ba4887cf45b283974be5cb93260f4dd4feb588cc2d591534"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d5c0988bd65d08b91ad6947013af415347c4adc951bd7936c837da164dbedf0"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f190853d3bf80b2c72f08dd4095f4b7e7c1d0c8ac31a32c864b0c309a38c7dd"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kapten"
  desc "Manage Kapten resources from the command line"
  homepage "https://github.com/kapten-io/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapten"
  binary "restish-mcp"
end
