# This file was generated by cli/scripts/release-cask. DO NOT EDIT.
cask "kapten" do
  version "0.1.0-rc.2"

  on_macos do
    on_arm do
      sha256 "b61466b381d7ea25fa35b865b31db12a8b780523ebaf74eaa44757cbb984f3a7"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4f4599895f81e671a1f53b3e534c23bdca815887c35ccf48233a42a17b360fb"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "96f73fddaee25b197aa8817d4defe88ea7f0b47ff55f34146bbf8f6e46272214"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f926f7bb26f0fc5e681fc80317879e89be543d39d25806995e4adefc2b8297e"
      url "https://github.com/kapten-io/cli/releases/download/v#{version}/kapten_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kapten"
  desc "Manage Kapten resources from the command line"
  homepage "https://github.com/kapten-io/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapten"
end
